### ISSUE TITLE
example config.json entry?

### ISSUE THREAD

**Issue by dkossman** [Supereg/homebridge-http-fanv2#1]
Hello,

i'm hoping i can use your plugin to control a variable speed pool pump (using nodeJsPoolController).

can you provide an example config.json entry?  it would be great if there was a README.   
apologies if I missed this somewhere.

thanks

**Comment by bauer-andreas** [comment]
Here would be a example configuration. Hope this helps. This lists all possible options.
Sadly this project isn't really maintained and the configuration isn't really that flexible.
`rotationSpeed` is optional. If rotationSpeed is used though %s will be replaced with the current value in the url. the statusUrl expects the response of the http call to deliver the current rotation speed in the body without any html markup. all `httpMethod` properties are optional.

```json
{
    "accessories": [
        {
            "accessory": "HTTP-FAN-V2",
            "name": "Your desired name",
            "active": {
                "httpMethod": "GET", // optional, default is GET

                "onUrl": "http://example.com/turningOn",
                "offUrl": "http://example.com/turningOff",
                "statusUrl": "http://example.com/currentOnStatus"
            },
            "rotationSpeed": {
                "httpMethod": "GET", // optional, default is GET

                "setUrl": "http://example.com/setRotation?to=%s",
                "statusUrl": "http://example.com/getCurrentRotationSpeed"
            }
        }
    ]
}
```
