### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by ixy05** [Supereg/homebridge-http-fanv2#3]
this looks promising but i dont know how to use it? any instructions avalible?

**Comment by alodyakov** [comment]
{
    "accessory": "HTTP-FAN-V2",
    "name": "fan_new",
    "active": {
        "onUrl": "http://localhost/on",
        "offUrl": "http://localhost/Off",
        "statusUrl": "http://localhost/Status"
    },
    "rotationSpeed": {
        "setUrl": "http://localhost/s=%s",
        "statusUrl": "http://localhost/status"
    }
}
